apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs-container
        image: saitadikonda99/docker-next:latest
        ports:
        - containerPort: 3000
