import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from "react-hot-toast";
import AuthProvider from './context/AuthProvider'  

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Project Management System',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-right" />
          {children}
      </body>
    </html>
  )
}

